                  <form action="message.php" method="post">
                     <div class="form-group"> <label for="first_name">First Name</label> <input type="text" class="form-control" id="first_name" name="first_name" required> </div>
                     <div class="form-group"> <label for="last_name">Last Name</label> <input type="text" class="form-control" id="last_name" name="last_name" required> </div>
                     <div class="form-group"> <label for="company">Company</label> <input type="text" class="form-control" id="company" name="company" required> </div>
                     <div class="form-group"> <label for="email">Email Address</label> <input type="email" class="form-control" id="email" name="email" required></div>
                     <div class="form-group" <label for="other_reason">Message</label> 
                     <textarea class="form-control" id="message" name="message" required></textarea>
               </div>
               <button type="submit" class="btn btn-primary mt-3">Submit</button>
               </form>